Update dependency org.springframework:spring-framework-bom to v6.2.12 (#92)
This PR contains the following updates:

| Package | Change | Age | Confidence |
|---|---|---|---|
|
[org.springframework:spring-framework-bom](https://redirect.github.com/spring-projects/spring-framework)
| `6.2.11` -> `6.2.12` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework:spring-framework-bom/6.2.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework:spring-framework-bom/6.2.11/6.2.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>spring-projects/spring-framework
(org.springframework:spring-framework-bom)</summary>

###
[`v6.2.12`](https://redirect.github.com/spring-projects/spring-framework/releases/tag/v6.2.12)

[Compare
Source](https://redirect.github.com/spring-projects/spring-framework/compare/v6.2.11...v6.2.12)

##### :star: New Features

- Add "forEachByte" variant to DataBuffer for efficient traversing
[#&#8203;35623](https://redirect.github.com/spring-projects/spring-framework/issues/35623)
- Nested transaction support via savepoints is broken in HSQLDB database
\[followup]
[#&#8203;35618](https://redirect.github.com/spring-projects/spring-framework/issues/35618)
- Improve exception handling in `ConfigurationClassBeanDefinitionReader`
[#&#8203;35631](https://redirect.github.com/spring-projects/spring-framework/issues/35631)
- Add MySQL/MariaDB to TableMetaDataProviderFactory for correct
generated-keys support
[#&#8203;35593](https://redirect.github.com/spring-projects/spring-framework/issues/35593)
- Optimize state management in StompSubProtocolHandler
[#&#8203;35591](https://redirect.github.com/spring-projects/spring-framework/issues/35591)
- ServletServerHttpRequest.getRemoteAddress() may perform DNS lookup
[#&#8203;35589](https://redirect.github.com/spring-projects/spring-framework/issues/35589)
- Emit log message when multiple primary beans are detected
[#&#8203;35550](https://redirect.github.com/spring-projects/spring-framework/issues/35550)
- Duplicate key error is mapped to `TransientDataAccessException` by
`SQLStateSQLExceptionTranslator` for `BatchUpdateException`
[#&#8203;35547](https://redirect.github.com/spring-projects/spring-framework/issues/35547)
- Remove redundant object allocation in cglib proxy method calls
[#&#8203;35543](https://redirect.github.com/spring-projects/spring-framework/pull/35543)
- Remove deprecation on `CandidateComponentsIndex` and
`CandidateComponentsIndexLoader`
[#&#8203;35472](https://redirect.github.com/spring-projects/spring-framework/issues/35472)
- Processing response with no Content-Length header and no body raises
EOFException
[#&#8203;35361](https://redirect.github.com/spring-projects/spring-framework/issues/35361)

##### :lady\_beetle: Bug Fixes

- DefaultListableBeanFactory::getBeanNamesForType does not always return
all bean names
[#&#8203;35634](https://redirect.github.com/spring-projects/spring-framework/issues/35634)
- Consider defaultCandidate for scoped proxies
[#&#8203;35627](https://redirect.github.com/spring-projects/spring-framework/pull/35627)
- Release data buffer in AbstractCharSequenceDecoder even when String
creation fails
[#&#8203;35625](https://redirect.github.com/spring-projects/spring-framework/pull/35625)
- PathMatchingResourcePatternResolver is not able to resolve file in
SpringBoot Packaged JAR
[#&#8203;35617](https://redirect.github.com/spring-projects/spring-framework/issues/35617)
- Prevent NoClassDefFoundError when Jetty Reactive HttpClient is not
available
[#&#8203;35608](https://redirect.github.com/spring-projects/spring-framework/pull/35608)
- Performance regression with Property Placeholder Resolution
[#&#8203;35594](https://redirect.github.com/spring-projects/spring-framework/issues/35594)
- Retain order of `produces` media types in `@ExceptionHandler`
[#&#8203;35587](https://redirect.github.com/spring-projects/spring-framework/pull/35587)
- Nested transaction support via savepoints is broken in HSQLDB database
[#&#8203;35564](https://redirect.github.com/spring-projects/spring-framework/issues/35564)
- SpEL expression parser uses more CPU after upgrade to 6.2.9
[#&#8203;35556](https://redirect.github.com/spring-projects/spring-framework/issues/35556)
- Thread race during FactoryBean instantiations starting with 6.2 due to
lenient locks
[#&#8203;35545](https://redirect.github.com/spring-projects/spring-framework/issues/35545)
- Update parsed path handling in UrlHandlerFilter
[#&#8203;35538](https://redirect.github.com/spring-projects/spring-framework/issues/35538)
- ResourceHttpMessageWriter.write has unexpected error handling for
invalid range requests (offset > content length)
[#&#8203;35536](https://redirect.github.com/spring-projects/spring-framework/issues/35536)
- `AbstractTestNGSpringContextTests` is not thread-safe regarding
tracked exceptions
[#&#8203;35528](https://redirect.github.com/spring-projects/spring-framework/issues/35528)
- UrlHandlerFilter breaks RequestDispatcher.forward() on Tomcat
[#&#8203;35509](https://redirect.github.com/spring-projects/spring-framework/issues/35509)
- AbstractMockHttpServletRequestBuilder#buildRequest is not idempotent
[#&#8203;35493](https://redirect.github.com/spring-projects/spring-framework/pull/35493)
- Add support for `JvmDefault` (default in Kotlin 2.2.20+)
[#&#8203;35487](https://redirect.github.com/spring-projects/spring-framework/issues/35487)
- InstanceSupplierCodeGenerator fails to detect deprecated type on
package private factory method
[#&#8203;35486](https://redirect.github.com/spring-projects/spring-framework/issues/35486)
- Fix synchronization in ResponseBodyEmitter
[#&#8203;35466](https://redirect.github.com/spring-projects/spring-framework/issues/35466)
- useCaches option in PathMatchingResourcePatternResolver not applied in
special case
[#&#8203;35465](https://redirect.github.com/spring-projects/spring-framework/pull/35465)
- Deadlock during context initialization due to EntityManager lock
[#&#8203;35398](https://redirect.github.com/spring-projects/spring-framework/issues/35398)

##### :notebook\_with\_decorative\_cover: Documentation

- Improve guidance in WebFlux on how to join inbound and outbound
streams in `WebSocketHandler`
[#&#8203;35572](https://redirect.github.com/spring-projects/spring-framework/issues/35572)
- Fix `idref` example in reference manual
[#&#8203;35560](https://redirect.github.com/spring-projects/spring-framework/issues/35560)
- Fix URI Patterns docs in WebMVC and WebFlux Request Mapping
[#&#8203;35551](https://redirect.github.com/spring-projects/spring-framework/pull/35551)
- Allow event listener method declared with multiple event classes to
take a single parameter that is assignable from all of those event
classes
[#&#8203;35506](https://redirect.github.com/spring-projects/spring-framework/issues/35506)
- Improve Task Javadoc about Runnable wrapping
[#&#8203;35394](https://redirect.github.com/spring-projects/spring-framework/issues/35394)

##### :hammer: Dependency Upgrades

- Upgrade to Micrometer 1.14.12
[#&#8203;35640](https://redirect.github.com/spring-projects/spring-framework/issues/35640)
- Upgrade to Reactor 2024.0.11
[#&#8203;35638](https://redirect.github.com/spring-projects/spring-framework/issues/35638)

##### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;Entea](https://redirect.github.com/Entea),
[@&#8203;IMurzich](https://redirect.github.com/IMurzich),
[@&#8203;hosea](https://redirect.github.com/hosea),
[@&#8203;maziyarbahramian](https://redirect.github.com/maziyarbahramian),
[@&#8203;mlichtblau](https://redirect.github.com/mlichtblau),
[@&#8203;nstdio](https://redirect.github.com/nstdio),
[@&#8203;reckart](https://redirect.github.com/reckart), and
[@&#8203;reda-alaoui](https://redirect.github.com/reda-alaoui)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/kpavlov/langfuse-jvm).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0MS4xNDMuMSIsInVwZGF0ZWRJblZlciI6IjQxLjE0My4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>