Update dependency org.springframework:spring-framework-bom to v6.2.6 (#42)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[org.springframework:spring-framework-bom](https://redirect.github.com/spring-projects/spring-framework)
| `6.2.5` -> `6.2.6` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/org.springframework:spring-framework-bom/6.2.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.springframework:spring-framework-bom/6.2.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.springframework:spring-framework-bom/6.2.5/6.2.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.springframework:spring-framework-bom/6.2.5/6.2.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>spring-projects/spring-framework
(org.springframework:spring-framework-bom)</summary>

###
[`v6.2.6`](https://redirect.github.com/spring-projects/spring-framework/releases/tag/v6.2.6)

[Compare
Source](https://redirect.github.com/spring-projects/spring-framework/compare/v6.2.5...v6.2.6)

#### :star: New Features

- An option for SimpleAsyncTaskExecutor to throw an exception when limit
is reached
[#&#8203;34727](https://redirect.github.com/spring-projects/spring-framework/issues/34727)
- Provide first-class support for Bean Overrides with
`@ContextHierarchy`
[#&#8203;34723](https://redirect.github.com/spring-projects/spring-framework/pull/34723)
- Micro performance optimizations
[#&#8203;34717](https://redirect.github.com/spring-projects/spring-framework/pull/34717)
- Suppress "Unable to rollback against JDBC Connection" in case of
timeout (connection closed)
[#&#8203;34714](https://redirect.github.com/spring-projects/spring-framework/issues/34714)
- Avoid early FactoryBean instantiation for type-based retrieval with
includeNonSingletons=false and allowEagerInit=true
[#&#8203;34710](https://redirect.github.com/spring-projects/spring-framework/issues/34710)
- ReactiveCachingHandler still not using error handler on sync cache.
[#&#8203;34708](https://redirect.github.com/spring-projects/spring-framework/issues/34708)
- Add an `exchangeForRequiredValue` variant to `RestClient`
[#&#8203;34692](https://redirect.github.com/spring-projects/spring-framework/issues/34692)
- Recursively boxing Kotlin nested value classes in `CoroutinesUtils`
[#&#8203;34682](https://redirect.github.com/spring-projects/spring-framework/pull/34682)
- ServletServerHttpRequest does not use charset parameter of
application/x-www-form-urlencoded
[#&#8203;34675](https://redirect.github.com/spring-projects/spring-framework/issues/34675)
- LifecycleGroup concurrent start and start timeout
[#&#8203;34634](https://redirect.github.com/spring-projects/spring-framework/issues/34634)
- HibernateJpaDialect exception translation misses concrete exceptions
wrapped in Hibernate's ExecutionException
[#&#8203;34633](https://redirect.github.com/spring-projects/spring-framework/issues/34633)

#### :lady_beetle: Bug Fixes

- Inconsistency in `SseEmitter.onCompletion()` behavior between Spring
6.2.3 and 6.2.5
[#&#8203;34762](https://redirect.github.com/spring-projects/spring-framework/issues/34762)
- Deadlock while creating Spring beans with parallel bootstrap threads
on IBM Liberty
[#&#8203;34729](https://redirect.github.com/spring-projects/spring-framework/issues/34729)
- `PropertyBatchUpdateException`: causes of nested
`PropertyAccessException`s not shown in output
[#&#8203;34691](https://redirect.github.com/spring-projects/spring-framework/issues/34691)
- IllegalAccessError for package-private member of
AzureStorageConfiguration on WebSphere
[#&#8203;34684](https://redirect.github.com/spring-projects/spring-framework/issues/34684)
- Change in Jar usecache behavior with Spring 6.1.x causing
java.lang.IllegalStateException: zip file closed
[#&#8203;34678](https://redirect.github.com/spring-projects/spring-framework/issues/34678)
- Startup performance regression due to CGLIB class load attempts in
Spring 6.1.x
[#&#8203;34677](https://redirect.github.com/spring-projects/spring-framework/issues/34677)
- An infinite wait on a parallel context.getBean()
[#&#8203;34672](https://redirect.github.com/spring-projects/spring-framework/issues/34672)
- InvalidObservationException: Invalid start: Observation
'http.client.requests' has already been started
[#&#8203;34671](https://redirect.github.com/spring-projects/spring-framework/issues/34671)
- `@Configuration` classes can no longer be `abstract` without `@Bean`
methods
[#&#8203;34663](https://redirect.github.com/spring-projects/spring-framework/issues/34663)
- Generated-code for LinkedHashMap is missing static keyword
[#&#8203;34659](https://redirect.github.com/spring-projects/spring-framework/issues/34659)
- Detect late-set primary markers for autowiring shortcut algorithm
[#&#8203;34658](https://redirect.github.com/spring-projects/spring-framework/issues/34658)
- `@MockitoBean` with custom `@Qualifier` is not injected into
`@Configuration` class
[#&#8203;34646](https://redirect.github.com/spring-projects/spring-framework/issues/34646)
- Qualifier Resolution Issue in Parent-Child Context Hierarchies
[#&#8203;34644](https://redirect.github.com/spring-projects/spring-framework/issues/34644)
- Enforced container-level acknowledge call for custom acknowledgement
mode
[#&#8203;34635](https://redirect.github.com/spring-projects/spring-framework/issues/34635)
- UriComponentsBuilder does not treat a URN as opaque if it contains a
slash
[#&#8203;34588](https://redirect.github.com/spring-projects/spring-framework/issues/34588)
- Migrating from Spring 6.1.x to 6.2.x leads to exceptions in a Pekko
setup
[#&#8203;34303](https://redirect.github.com/spring-projects/spring-framework/issues/34303)

#### :notebook_with_decorative_cover: Documentation

- Update Javadoc for `ignoreDependencyInterface()` in
`AbstractAutowireCapableBeanFactory`
[#&#8203;34747](https://redirect.github.com/spring-projects/spring-framework/pull/34747)
- Update Javadoc to stop mentioning 5.3.x as the status quo
[#&#8203;34740](https://redirect.github.com/spring-projects/spring-framework/issues/34740)
- Fix broken link for Server-Sent Events
[#&#8203;34705](https://redirect.github.com/spring-projects/spring-framework/pull/34705)
- Fix typo in Bean Validation section of reference manual
[#&#8203;34686](https://redirect.github.com/spring-projects/spring-framework/pull/34686)
- Remove unnecessary closing curly brackets in Javadoc
[#&#8203;34679](https://redirect.github.com/spring-projects/spring-framework/pull/34679)
- Add javadoc notes on potential exception suppression in
`ListableBeanFactory#getBeansOfType`
[#&#8203;34629](https://redirect.github.com/spring-projects/spring-framework/issues/34629)
- Remove remaining references to Forwarded headers in
MvcUriComponentsBuilder
[#&#8203;34625](https://redirect.github.com/spring-projects/spring-framework/issues/34625)

#### :heart: Contributors

Thank you to all the contributors who worked on this release:

[@&#8203;acktsap](https://redirect.github.com/acktsap),
[@&#8203;dmitrysulman](https://redirect.github.com/dmitrysulman),
[@&#8203;iggzq](https://redirect.github.com/iggzq),
[@&#8203;izeye](https://redirect.github.com/izeye),
[@&#8203;ngocnhan-tran1996](https://redirect.github.com/ngocnhan-tran1996),
[@&#8203;obourgain](https://redirect.github.com/obourgain), and
[@&#8203;tobias-haenel](https://redirect.github.com/tobias-haenel)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/kpavlov/langfuse-jvm).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yMzguMCIsInVwZGF0ZWRJblZlciI6IjM5LjIzOC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>